SELECT CUST_CODE, BEFORE_SHOP_DATE, PREVIOUS_SHOP_YEAR, PREVIOUS_SHOP_MONTH, SHOP_YEAR, SHOP_MONTH,
CASE WHEN SHOP_YEAR IS NOT NULL AND PREVIOUS_SHOP_YEAR IS NOT NULL THEN 'REPEAT'
WHEN SHOP_YEAR IS NOT NULL AND PREVIOUS_SHOP_YEAR IS NULL AND BEFORE_SHOP_DATE IS NOT NULL THEN 'REACTIVATED'
WHEN SHOP_YEAR IS NOT NULL AND PREVIOUS_SHOP_YEAR IS NULL AND BEFORE_SHOP_DATE IS NULL THEN 'NEW'
WHEN SHOP_YEAR IS NULL AND PREVIOUS_SHOP_YEAR IS NOT NULL THEN 'CHURN'
END as CUST_MOVEMENT_TYPE,
case when SHOP_YEAR is not null and length(cast(SHOP_MONTH as string)) = 2 THEN DATE_TRUNC(DATE_ADD(PARSE_DATE('%Y%m%d', CONCAT(SHOP_YEAR, SHOP_MONTH, '01')), INTERVAL 1 MONTH), MONTH) 
when SHOP_YEAR is not null and length(cast(SHOP_MONTH as string)) = 1 THEN DATE_TRUNC(DATE_ADD(PARSE_DATE('%Y%m%d', CONCAT(SHOP_YEAR, '0', SHOP_MONTH, '01')), INTERVAL 1 MONTH), MONTH)
when SHOP_YEAR is null and PREVIOUS_SHOP_YEAR is not null and length(cast(PREVIOUS_SHOP_MONTH as string)) = 2 THEN DATE_TRUNC(DATE_ADD(PARSE_DATE('%Y%m%d', CONCAT(PREVIOUS_SHOP_YEAR, PREVIOUS_SHOP_MONTH, '01')), INTERVAL 1 MONTH), MONTH)
when SHOP_YEAR is null and PREVIOUS_SHOP_YEAR is not null and length(cast(PREVIOUS_SHOP_MONTH as string)) = 1 THEN DATE_TRUNC(DATE_ADD(PARSE_DATE('%Y%m%d', CONCAT(PREVIOUS_SHOP_YEAR, '0', PREVIOUS_SHOP_MONTH, '01')), INTERVAL 1 MONTH), MONTH)
end as CURRENT_MONTH
FROM
    (SELECT main.CUST_CODE,
    max(case when length(cast( b.CURRENT_SHOP_MONTH as string)) = 2 THEN PARSE_DATE('%Y%m%d', CONCAT(b.CURRENT_SHOP_YEAR, b.CURRENT_SHOP_MONTH, '01'))
    else PARSE_DATE('%Y%m%d', CONCAT(b.CURRENT_SHOP_YEAR, '0', b.CURRENT_SHOP_MONTH, '01')) 
    end) as BEFORE_SHOP_DATE,
    main.PREVIOUS_SHOP_YEAR,
    main.PREVIOUS_SHOP_MONTH,
    main.SHOP_YEAR,
    main.SHOP_MONTH
    FROM (
    SELECT DISTINCT main.CUST_CODE,

    EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING))) as SHOP_YEAR,
    EXTRACT(MONTH FROM PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING))) as SHOP_MONTH,
    a.CURRENT_SHOP_YEAR as PREVIOUS_SHOP_YEAR,
    a.CURRENT_SHOP_MONTH as PREVIOUS_SHOP_MONTH
    FROM nida-crm.supermarket.supermarket_transaction main

    FULL JOIN (SELECT DISTINCT CUST_CODE,
    PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)) as CURRENT_SHOP_DATE,
    EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) AS CURRENT_SHOP_YEAR,
    EXTRACT(MONTH FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) AS CURRENT_SHOP_MONTH
    FROM nida-crm.supermarket.supermarket_transaction 
    WHERE CUST_CODE IS NOT NULL) a
    on main.CUST_CODE = a.CUST_CODE AND 
    EXTRACT(YEAR FROM DATE_SUB(DATE_TRUNC(PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING)), MONTH), INTERVAL 1 DAY)) = a.CURRENT_SHOP_YEAR AND
    EXTRACT(MONTH FROM DATE_SUB(DATE_TRUNC(PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING)), MONTH), INTERVAL 1 DAY)) = a.CURRENT_SHOP_MONTH

    UNION ALL
    SELECT DISTINCT main.CUST_CODE, 
    a.CURRENT_SHOP_YEAR as SHOP_YEAR,
    a.CURRENT_SHOP_MONTH as SHOP_MONTH,
    EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING))) as PREVIOUS_SHOP_YEAR,
    EXTRACT(MONTH FROM PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING))) as PREVIOUS_SHOP_MONTH,
    FROM nida-crm.supermarket.supermarket_transaction main

    -- Current Shop Month
    LEFT JOIN (SELECT DISTINCT CUST_CODE,
    PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)) as CURRENT_SHOP_DATE,
    EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) AS CURRENT_SHOP_YEAR,
    EXTRACT(MONTH FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) AS CURRENT_SHOP_MONTH
    FROM nida-crm.supermarket.supermarket_transaction 
    WHERE CUST_CODE IS NOT NULL) a
    on main.CUST_CODE = a.CUST_CODE AND 
    EXTRACT(YEAR FROM DATE_TRUNC(DATE_ADD(PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING)), INTERVAL 1 MONTH), MONTH)) = a.CURRENT_SHOP_YEAR AND
    EXTRACT(MONTH FROM DATE_TRUNC(DATE_ADD(PARSE_DATE('%Y%m%d', CAST(main.SHOP_DATE AS STRING)), INTERVAL 1 MONTH), MONTH)) = a.CURRENT_SHOP_MONTH

    ) main
-- Before Shopping Date
LEFT JOIN (SELECT DISTINCT CUST_CODE,
PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)) as CURRENT_SHOP_DATE,
EXTRACT(YEAR FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) AS CURRENT_SHOP_YEAR,
EXTRACT(MONTH FROM PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING))) AS CURRENT_SHOP_MONTH
FROM nida-crm.supermarket.supermarket_transaction 
WHERE CUST_CODE IS NOT NULL) b
on main.CUST_CODE = b.CUST_CODE AND 
main.SHOP_YEAR  >= b.CURRENT_SHOP_YEAR AND
main.SHOP_MONTH > b.CURRENT_SHOP_MONTH

GROUP BY main.CUST_CODE,
main.PREVIOUS_SHOP_YEAR,
main.PREVIOUS_SHOP_MONTH,
main.SHOP_YEAR,
main.SHOP_MONTH

)
ORDER BY CUST_CODE, SHOP_YEAR, SHOP_MONTH DESC